name: 🔍 Check iOS Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    name: 🔍 Check Required Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: 📋 Check Secrets Configuration
        run: |
          echo "🔍 Checking required secrets for iOS deployment..."
          echo ""
          
          # Function to check if secret is set
          check_secret() {
            local secret_name=$1
            local secret_value=$2
            if [ -z "$secret_value" ]; then
              echo "❌ $secret_name - NOT SET"
              return 1
            else
              echo "✅ $secret_name - SET (length: ${#secret_value})"
              return 0
            fi
          }
          
          # Track if all secrets are present
          all_secrets_present=true
          
          echo "📱 Certificate & Provisioning:"
          check_secret "BUILD_CERTIFICATE_BASE64" "${{ secrets.BUILD_CERTIFICATE_BASE64 }}" || all_secrets_present=false
          check_secret "P12_PASSWORD" "${{ secrets.P12_PASSWORD }}" || all_secrets_present=false
          check_secret "KEYCHAIN_PASSWORD" "${{ secrets.KEYCHAIN_PASSWORD }}" || all_secrets_present=false
          check_secret "BUILD_PROVISION_PROFILE_BASE64" "${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}" || all_secrets_present=false
          check_secret "PROVISION_PROFILE_UUID" "${{ secrets.PROVISION_PROFILE_UUID }}" || all_secrets_present=false
          
          echo ""
          echo "🔑 App Store Connect API:"
          check_secret "APP_STORE_CONNECT_API_KEY_ID" "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}" || all_secrets_present=false
          check_secret "APP_STORE_CONNECT_API_KEY_ISSUER_ID" "${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}" || all_secrets_present=false
          check_secret "APP_STORE_CONNECT_API_KEY_KEY" "${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}" || all_secrets_present=false
          
          echo ""
          if [ "$all_secrets_present" = true ]; then
            echo "✅ All required secrets are configured!"
            echo ""
            echo "📝 Next steps:"
            echo "1. Run the 'iOS TestFlight Deploy' workflow"
            echo "2. If it still fails, check the workflow logs for specific errors"
          else
            echo "❌ Some secrets are missing!"
            echo ""
            echo "📝 To fix this:"
            echo "1. Go to Settings → Secrets and variables → Actions"
            echo "2. Add the missing secrets listed above"
            echo "3. For detailed instructions, see docs/ci-cd/GITHUB_SECRETS_SETUP.md"
            exit 1
          fi 