name: Deploy to Railway

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_pgsql, dom, filter, gd, json, mbstring, pdo
          tools: composer:v2
      
      - name: Validate composer.json
        run: composer validate --strict
      
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
      
      - name: Run tests
        run: ./test-quick.sh
        continue-on-error: true
      
      - name: Deploy to Railway
        uses: berviantoleo/railway-deploy@v1.0.1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: lms-backend
      
      - name: Run migrations on Railway
        run: |
          npm install -g @railway/cli
          railway run --service lms-backend php artisan migrate --force
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 