disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - closure_spacing

excluded:
  - .build
  - Tests
  - Package.swift

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
