apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
      version: v1
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: lms/api-gateway:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: RATE_LIMIT_REDIS_URL
          value: redis://redis-service:6379
        - name: CORS_ALLOWED_ORIGINS
          value: "https://lms.tsum.ru,https://app.lms.tsum.ru"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 443
    targetPort: 8443
    name: https
  selector:
    app: api-gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  routes.yaml: |
    routes:
      - path: /api/v1/auth
        service: auth-service
        port: 8080
        methods: ["GET", "POST", "PUT", "DELETE"]
      - path: /api/v1/users
        service: user-service
        port: 8080
        methods: ["GET", "POST", "PUT", "DELETE"]
      - path: /api/v1/courses
        service: course-service
        port: 8080
        methods: ["GET", "POST", "PUT", "DELETE"]
      - path: /api/v1/competencies
        service: competency-service
        port: 8080
        methods: ["GET", "POST", "PUT", "DELETE"]
      - path: /api/v1/notifications
        service: notification-service
        port: 8080
        methods: ["GET", "POST", "PUT", "DELETE"]
      - path: /api/v1/org-structure
        service: org-structure-service
        port: 8080
        methods: ["GET", "POST", "PUT", "DELETE"]
    middleware:
      - type: authentication
        paths: ["/api/v1/*"]
        exclude: ["/api/v1/auth/login", "/api/v1/auth/refresh"]
      - type: rate-limiting
        requests_per_minute: 100
        burst: 20
      - type: cors
        max_age: 86400
      - type: compression
        min_size: 1024 