apiVersion: apps/v1
kind: Deployment
metadata:
  name: competency-service
  labels:
    app: competency-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: competency-service
      version: v1
  template:
    metadata:
      labels:
        app: competency-service
        version: v1
    spec:
      containers:
      - name: competency-service
        image: lms/competency-service:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: competency-db-secret
              key: host
        - name: DB_NAME
          value: competency_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: competency-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: competency-db-secret
              key: password
        - name: REDIS_URL
          value: redis://redis-service:6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: competency-service
  labels:
    app: competency-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: competency-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: competency-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: competency-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 