name: iOS Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Run tests
      run: |
        cd LMS_App/LMS
        xcodebuild test \
          -scheme LMS \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -resultBundlePath TestResults \
          | xcpretty --color --report junit
          
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: LMS_App/LMS/TestResults 