name: PR Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: Build and Test
      run: |
        cd LMS_App/LMS
        set -o pipefail
        xcodebuild test \
          -scheme LMS \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          | xcpretty --report junit
          
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: |
          LMS_App/LMS/build/reports/junit.xml 