#!/bin/bash

echo "📱 LMS TestFlight Archive Guide"
echo "=============================="
echo ""
echo "Due to Info.plist configuration issues, please follow these manual steps:"
echo ""
echo "STEP 1: Open Xcode"
echo "  open LMS.xcodeproj"
echo ""
echo "STEP 2: In Xcode:"
echo "  a) Click on the project (blue icon) in navigator"
echo "  b) Select 'LMS' target"
echo "  c) Go to 'Build Phases' tab"
echo "  d) Expand 'Copy Bundle Resources'"
echo "  e) If you see 'Info.plist' there - select it and click '-' to remove"
echo "  f) Save project (Cmd+S)"
echo ""
echo "STEP 3: Select destination"
echo "  In the scheme selector at the top, choose 'Any iOS Device (arm64)'"
echo ""
echo "STEP 4: Archive"
echo "  Product → Archive (or Cmd+Shift+I)"
echo ""
echo "STEP 5: Upload to TestFlight"
echo "  a) When archive completes, Organizer will open"
echo "  b) Select your archive"
echo "  c) Click 'Distribute App'"
echo "  d) Choose 'TestFlight & App Store'"
echo "  e) Follow the upload wizard"
echo ""
echo "----------------------------------------"
echo "ALTERNATIVE: Use working commit"
echo ""
echo "If the above doesn't work, use the last working version:"
echo "  git stash"
echo "  git checkout 2eaa210e"
echo "  xcodebuild archive -scheme LMS -archivePath build/LMS.xcarchive"
echo ""
echo "----------------------------------------"
echo ""
echo "Would you like to open Xcode now? (y/n)"
read -r response

if [[ "$response" =~ ^[Yy]$ ]]; then
    open LMS.xcodeproj
fi 