#!/bin/bash

echo "🔧 Исправление привязки ViewInspector к LMSTests"
echo "=============================================="
echo ""
echo "⚠️  ViewInspector добавлен, но не привязан к таргету LMSTests!"
echo ""
echo "📋 Быстрые шаги в Xcode:"
echo ""
echo "1️⃣  Кликните на LMS (корневой проект)"
echo "2️⃣  Выберите ТАРГЕТ 'LMSTests' (не проект!)"
echo "3️⃣  Вкладка 'General'"
echo "4️⃣  В секции 'Frameworks and Libraries' нажмите '+'"
echo "5️⃣  Найдите и добавьте 'ViewInspector'"
echo ""
echo "ИЛИ:"
echo ""
echo "1️⃣  Кликните на LMS → Package Dependencies"
echo "2️⃣  Дважды кликните на ViewInspector"
echo "3️⃣  Убедитесь, что галочка стоит у LMSTests"
echo ""
echo "После исправления:"
echo "- Cmd+Shift+K (Clean)"
echo "- Cmd+B (Build)"
echo ""
echo "🚀 Затем запустите: ./run-tests-with-coverage.sh" 