platform :ios, '18.0'

target 'LMS' do
  use_frameworks!

  # VK ID SDK
  pod 'VKID'
  pod 'VKIDCore'

  target 'LMSTests' do
    inherit! :search_paths
  end

  target 'LMSUITests' do
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end

